; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march upt -verify-machineinstrs -show-mc-encoding <  %s \
; RUN:   | FileCheck %s --check-prefix=ALU


define i32 @addi_big(i32 %a) nounwind {
; ALU-LABEL: addi_big:
; ALU:     # %bb.0:
; ALU-NEXT:   MOVL V0, 0         # encoding: [0x00,0x00,0x20,0x40]
; ALU-NEXT:   MOVU V0, 1         # encoding: [0x01,0x00,0x20,0x44]
; ALU-NEXT:   ADDR V0, A0, V0    # encoding: [0x00,0x08,0x22,0x18]
; ALU-NEXT:   RET                # encoding: [0x00,0x00,0xe0,0x4d]
  %1 = add i32 %a, 65536
  ret i32 %1
}



