; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march upt -verify-machineinstrs  <  %s \
; RUN:   | FileCheck %s --check-prefix=CALL


define i32 @and(i32, i32) #1 {
  %3 = add i32 %0,%1
  ret i32 %3
}
define i32 @call_test(i32 %a, i32 %b) #0 {
; CALL-LABEL call_test:
; CALL:      # %bb.0:
; CALL-NEXT:	  SUBI SP, SP, 4
; CALL-NEXT:	  STR  RA, [SP]
; CALL-NEXT:      # ADJCALLSTACKDOWN 0 0
; CALL-NEXT:	  MOVL {{[A-Z][0-9]}}, and
; CALL-NEXT:	  MOVU {{[A-Z][0-9]}}, and
; CALL-NEXT:	  CALL {{[A-Z][0-9]}}
; CALL-NEXT:      # ADJCALLSTACKUP 0 0
; CALL-NEXT:	  LDR  RA, [SP]
; CALL-NEXT:	  ADDI SP, SP, 4
; CALL-NEXT:	  RET
  %call = call i32 @and(i32 %a, i32 %b)
  ret i32 %call
}


