; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc  -march upt -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s



define  i32 @mul(i32 %a, i32 %b) nounwind {
  %1 = mul i32 %a, %b
  ret i32 %1
}

define  i32 @mul_constant(i32 %a) nounwind {
  %1 = mul i32 %a, 5
  ret i32 %1
}

define i32 @mul_pow2(i32 %a) nounwind {
  %1 = mul i32 %a, 8
  ret i32 %1
}

define i32 @div_pow2(i32 %a) nounwind {
  %1 = sdiv i32 %a, 8
  ret i32 %1
}

define i32 @mulhs(i32 %a, i32 %b) nounwind {
  %1 = sext i32 %a to i64
  %2 = sext i32 %b to i64
  %3 = mul i64 %1, %2
  %4 = lshr i64 %3, 32
  %5 = trunc i64 %4 to i32
  ret i32 %5
}

define zeroext i32 @mulhu(i32 zeroext %a, i32 zeroext %b) nounwind {
; RV32I-LABEL: mulhu:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -16
; RV32I-NEXT:    sw ra, 12(sp)
; RV32I-NEXT:    mv a2, a1
; RV32I-NEXT:    mv a1, zero
; RV32I-NEXT:    mv a3, zero
; RV32I-NEXT:    call __muldi3
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    lw ra, 12(sp)
; RV32I-NEXT:    addi sp, sp, 16
; RV32I-NEXT:    ret
;
; RV32IM-LABEL: mulhu:
; RV32IM:       # %bb.0:
; RV32IM-NEXT:    mulhu a0, a0, a1
; RV32IM-NEXT:    ret
;
  %1 = zext i32 %a to i64
  %2 = zext i32 %b to i64
  %3 = mul i64 %1, %2
  %4 = lshr i64 %3, 32
  %5 = trunc i64 %4 to i32
  ret i32 %5
}
